// All interface text in one place.
export const t = {
  courses: 'Klassid',
  usefulLinks: 'Kasulikud lingid',
  noPosts: 'Materjale veel pole.',
  back: '← Kõik klassid',
  openLink: 'Ava link',
  viewPdf: 'Vaata',
  download: 'Laadi alla',
  openForm: 'Täida vorm',
  openNewTab: 'Ava uues aknas',
  video: 'Video',
  pdfLoading: 'Laadin PDF-i…',
  pdfError: 'PDF-i avamine ebaõnnestus.',
  pdfNotFound: 'Faili ei leitud.',
  types: {
    link: 'Link',
    video: 'Video',
    pdf: 'PDF',
    file: 'Fail',
    form: 'Vorm',
    game: 'Mäng',
  },
  codeGame: {
    title: {
      html: 'Harjutus: pane HTML kokku',
      css: 'Harjutus: pane CSS kokku',
    },
    hint: 'Klõpsa sõnal või lohista see lünka. Täidetud lüngal klõpsates saad sõna tagasi.',
    preview: 'Nii peaks tulemus välja nägema:',
    progress: (i: number, n: number) => `Ülesanne ${i}/${n}`,
    gap: 'Lünk',
    check: 'Kontrolli',
    next: 'Järgmine ülesanne',
    restart: 'Alusta otsast',
    correct: 'Õige! 🎉',
    allDone: 'Kõik ülesanded on tehtud! 🎉',
    fillAll: 'Täida enne kontrollimist kõik lüngad.',
    wrong: (n: number) =>
      `${n === 1 ? '1 lünk on' : `${n} lünka on`} valesti. Klõpsa punasel lüngal, et sõna tagasi võtta.`,
  },
  hexGame: {
    title: 'Värvimäng: kuueteistkümnendsüsteem',
    explore: 'Liiguta liugureid ja vaata, kuidas värvikood muutub.',
    red: 'Punane (R)',
    green: 'Roheline (G)',
    blue: 'Sinine (B)',
    question: (code: string) => `Millist värvi on ${code}?`,
    option: (n: number) => `Valik ${n}`,
    correct: 'Õige! 🎉',
    wrong: (code: string) => `See on ${code}. Mõtle, kui palju on koodis punast, rohelist ja sinist.`,
    next: 'Järgmine',
    score: (n: number) => `Õigeid: ${n}`,
  },
  binaryGame: {
    title: 'Mäng: kahend- ja kümnendsüsteem',
    toBinary: (n: number) => `Kirjuta arv ${n} kahendsüsteemis. Klõpsa bittidel.`,
    toDecimal: (b: string) => `Mis arv on ${b} kümnendsüsteemis?`,
    answer: 'Vastus',
    check: 'Kontrolli',
    next: 'Järgmine',
    correct: 'Õige! 🎉',
    wrongBinary: (n: number) => `Praegu on seal arv ${n}. Proovi veel!`,
    wrongDecimal: 'Pole päris õige. Liida kokku nende bittide väärtused, kus on 1.',
    score: (n: number) => `Õigeid: ${n}`,
    bits4: '4 bitti',
    bits8: '8 bitti',
  },
} as const;

export function formatDate(d: Date): string {
  return d.toLocaleDateString('et-EE', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  });
}
